<?php

namespace Database\Seeders;

use App\Models\District;
use App\Models\Kampong;
use App\Models\Mukim;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PostcodeSeeder extends Seeder
{
    /**
     * Seed Brunei postcodes (District -> Mukim -> Kampong).
     */
    public function run(): void
    {
        $dataset = [
            [
                'name' => 'Brunei-Muara',
                'mukims' => [
                    [
                        'name' => 'Berakas A',
                        'kampongs' => [
                            ['name' => 'Skim Tanah Kurnia Rakyat Jati Lambak Kiri', 'postcode' => 'BB1114'],
                            ['name' => 'Kampong Lambak Kiri', 'postcode' => 'BB1214'],
                            ['name' => 'Kampong Lambak A', 'postcode' => 'BB1314'],
                            ['name' => 'Kampong Terunjing', 'postcode' => 'BB1514'],
                            ['name' => 'Kampong Lambak B', 'postcode' => 'BB1714'],
                            ['name' => 'Kampong Serusop', 'postcode' => 'BB2313'],
                            ['name' => 'Lapangan Terbang Antarabangsa Brunei', 'postcode' => 'BB2513'],
                            ['name' => 'Kampong Jaya Setia', 'postcode' => 'BB2713'],
                            ['name' => 'Kampong Jaya Bakti', 'postcode' => 'BB3113'],
                            ['name' => 'Kampong Burong Pingai Berakas', 'postcode' => 'BB3313'],
                            ['name' => 'Kawasan Jabatan-Jabatan dan Perumahan Kerajaan', 'postcode' => 'BB3513'],
                            ['name' => 'Kampong Anggerek Desa', 'postcode' => 'BB3713'],
                            ['name' => 'Kampong Orang Kaya Besar Imas', 'postcode' => 'BB4113'],
                            ['name' => 'Kampong Pulaie', 'postcode' => 'BB4313'],
                            ['name' => 'Kampong Pancha Delima', 'postcode' => 'BB4513'],
                            ['name' => 'Kampung Pengiran Siraja Muda Delima Satu', 'postcode' => 'BB5113'],
                            ['name' => 'Perkhemahan Berakas', 'postcode' => 'BB1414'],
                        ],
                    ],
                    [
                        'name' => 'Berakas B',
                        'kampongs' => [
                            ['name' => 'Kampong Salambigar', 'postcode' => 'BC1515'],
                            ['name' => 'Kampong Sungai Orok', 'postcode' => 'BC1715'],
                            ['name' => 'Kampong Sungai Hanching', 'postcode' => 'BC2115'],
                            ['name' => 'Perumahan Negara Lambak Kanan Kawasan 1', 'postcode' => 'BC2315'],
                            ['name' => 'Perumahan Negara Lambak Kanan Kawasan 2', 'postcode' => 'BC2515'],
                            ['name' => 'Perumahan Negara Lambak Kanan Kawasan 3', 'postcode' => 'BC2715'],
                            ['name' => 'Perumahan Negara Lambak Kanan Kawasan 4', 'postcode' => 'BC2915'],
                            ['name' => 'Perumahan Negara Lambak Kanan Kawasan 5', 'postcode' => 'BC3115'],
                            ['name' => 'Kampong Sungai Tilong', 'postcode' => 'BC3315'],
                            ['name' => 'Kampong Manggis', 'postcode' => 'BC3615'],
                            ['name' => 'Kampong Madang', 'postcode' => 'BC3715'],
                            ['name' => 'Kampong Sungai Akar', 'postcode' => 'BC4115'],
                        ],
                    ],
                    [
                        'name' => 'Gadong A',
                        'kampongs' => [
                            ['name' => 'Kampong Tungku', 'postcode' => 'BE2119'],
                            ['name' => 'Kampong Katok', 'postcode' => 'BE2319'],
                            ['name' => 'Skim Tanah Kurnia Rakyat Jati Tungku Kawasan 1', 'postcode' => 'BE2519'],
                            ['name' => 'Skim Tanah Kurnia Rakyat Jati Tungku Kawasan 2', 'postcode' => 'BE2719'],
                            ['name' => 'Skim Tanah Kurnia Rakyat Jati Tungku Kawasan 3', 'postcode' => 'BE2919'],
                            ['name' => 'Kampong Rimba & Skim Tanah Kurnia Rakyat Jati Rimba', 'postcode' => 'BE3119'],
                            ['name' => 'Perumahan Negara Rimba Kawasan 1', 'postcode' => 'BE3319'],
                            ['name' => 'Perumahan Negara Rimba Kawasan 2', 'postcode' => 'BE3419'],
                            ['name' => 'Perumahan Negara Rimba Kawasan 3', 'postcode' => 'BE3519'],
                            ['name' => 'Perumahan Negara Rimba Kawasan 4', 'postcode' => 'BE3619'],
                            ['name' => 'Perumahan Negara Rimba Kawasan 5', 'postcode' => 'BE3819'],
                            ['name' => 'Hutan Simpan', 'postcode' => 'BE4719'],
                        ],
                    ],
                    [
                        'name' => 'Gadong B',
                        'kampongs' => [
                            ['name' => 'Kampong Beribi', 'postcode' => 'BE1118'],
                            ['name' => 'Kampong Kiarong', 'postcode' => 'BE1318'],
                            ['name' => 'Kampong Kiulap', 'postcode' => 'BE1518'],
                            ['name' => 'Kampong Mata-Mata', 'postcode' => 'BE1718'],
                            ['name' => 'Kampong Perpindahan Mata-Mata', 'postcode' => 'BE1918'],
                            ['name' => 'Kampong Pengkalan Gadong', 'postcode' => 'BE3719'],
                            ['name' => 'Kampong Menglait', 'postcode' => 'BE3919'],
                            ['name' => 'STKRJ Mata-Mata Kawasan 1', 'postcode' => 'BE2118'],
                            ['name' => 'STKRJ Mata-Mata Kawasan 2', 'postcode' => 'BE2318'],
                            ['name' => 'STKRJ Mata-Mata Kawasan 3', 'postcode' => 'BE2518'],
                        ],
                    ],
                    [
                        'name' => 'Kianggeh',
                        'kampongs' => [
                            ['name' => 'Kampong Berangan', 'postcode' => 'BA1111'],
                            ['name' => 'Kampong Kianggeh', 'postcode' => 'BA1211'],
                            ['name' => 'Kampong Tungkadeh', 'postcode' => 'BA1311'],
                            ['name' => 'Kampong Pusar Ulak', 'postcode' => 'BA1411'],
                            ['name' => 'Kampong Kumbang Pasang', 'postcode' => 'BA1511'],
                            ['name' => 'Kampong Tasek Lama', 'postcode' => 'BA1611'],
                            ['name' => 'Kampong Parit', 'postcode' => 'BA1912'],
                            ['name' => 'Kampong Tumasek', 'postcode' => 'BA2112'],
                            ['name' => 'Lingkungan Diplomatik', 'postcode' => 'BA2313'],
                            ['name' => 'Kampong Melabau', 'postcode' => 'BA2511'],
                            ['name' => 'PUSAT BANDAR', 'postcode' => 'BA8611'],
                        ],
                    ],
                    [
                        'name' => 'Kilanas',
                        'kampongs' => [
                            ['name' => 'Kampong Madewa', 'postcode' => 'BF1120'],
                            ['name' => 'Kampong Bunut', 'postcode' => 'BF1320'],
                            ['name' => 'Kampong Tasek Meradun', 'postcode' => 'BF1520'],
                            ['name' => 'Kampong Burong Lepas', 'postcode' => 'BF1720'],
                            ['name' => 'Kampong Bengkurong', 'postcode' => 'BF1920'],
                            ['name' => 'Kampong Sinarubai', 'postcode' => 'BF2120'],
                            ['name' => 'Kampong Kilanas', 'postcode' => 'BF2520'],
                            ['name' => 'Kampong Jangsak', 'postcode' => 'BF2720'],
                            ['name' => 'Kampong Tanjung Bunut', 'postcode' => 'BF2920'],
                            ['name' => 'Kampong Telanai', 'postcode' => 'BF1020'],
                            ['name' => 'Kampong Bunut Perpindahan', 'postcode' => 'BF1220'],
                            ['name' => 'Pulau Ranggu', 'postcode' => 'BF3520'],
                            ['name' => 'Pulau Luba', 'postcode' => 'BF3720'],
                        ],
                    ],
                    [
                        'name' => 'Kota Batu',
                        'kampongs' => [
                            ['name' => 'Kampong Sungai Lampai', 'postcode' => 'BD1117'],
                            ['name' => 'Kampong Pintu Malim', 'postcode' => 'BD1317'],
                            ['name' => 'Kampong Kota Batu', 'postcode' => 'BD1517'],
                            ['name' => 'Kampong Dato Gandi', 'postcode' => 'BD1717'],
                            ['name' => 'Kampong Gadong Batu', 'postcode' => 'BD1817'],
                            ['name' => 'Kampong Sungai Matan', 'postcode' => 'BD1917'],
                            ['name' => 'Kampong Serdang', 'postcode' => 'BD2117'],
                            ['name' => 'Kampong Sungai Belukut', 'postcode' => 'BD2217'],
                            ['name' => 'Kampong Pelambaian', 'postcode' => 'BD2317'],
                            ['name' => 'Kampong Sungai Besar', 'postcode' => 'BD2517'],
                            ['name' => 'Kampong Subok', 'postcode' => 'BD2717'],
                            ['name' => 'Kampong Belimbing', 'postcode' => 'BD2917'],
                            ['name' => 'Kampong Buang Tawar', 'postcode' => 'BD3017'],
                            ['name' => 'Kampong Tanjong Kindana', 'postcode' => 'BD3117'],
                            ['name' => 'Kampong Pudak', 'postcode' => 'BD3517'],
                            ['name' => 'Kampong Riong', 'postcode' => 'BD4117'],
                            ['name' => 'Kampong Menuggul', 'postcode' => 'BD4317'],
                            ['name' => 'Mengkubau', 'postcode' => 'BD4717'],
                            ['name' => 'Pulau Chermin', 'postcode' => 'BD4817'],
                            ['name' => 'Pulau Sibungur', 'postcode' => 'BD4917'],
                        ],
                    ],
                    [
                        'name' => 'Lumapas',
                        'kampongs' => [
                            ['name' => 'Kampong Putat', 'postcode' => 'BJ1324'],
                            ['name' => 'Kampong Baong', 'postcode' => 'BJ1424'],
                            ['name' => 'Kampong Kasat', 'postcode' => 'BJ1724'],
                            ['name' => 'Kampong Buang Sakar', 'postcode' => 'BJ1924'],
                            ['name' => 'Kampong Tarap Bau', 'postcode' => 'BJ2124'],
                            ['name' => 'Kampong Lupak Luas', 'postcode' => 'BJ2524'],
                            ['name' => 'Kampong Sungai Asam', 'postcode' => 'BJ2724'],
                            ['name' => 'Kampong Buang Tekurok', 'postcode' => 'BJ2924'],
                            ['name' => 'Kampong Lumapas', 'postcode' => 'BJ3324'],
                            ['name' => 'Kampong Panchor', 'postcode' => 'BJ3724'],
                            ['name' => 'Kampong Kilugus', 'postcode' => 'BJ3924'],
                            ['name' => 'STKRJ Kilugus', 'postcode' => 'BJ4124'],
                        ],
                    ],
                    [
                        'name' => 'Mentiri',
                        'kampongs' => [
                            ['name' => 'Kampong Tanah Jambu', 'postcode' => 'BU1129'],
                            ['name' => 'Kampong Salar', 'postcode' => 'BU1429'],
                            ['name' => 'Kampong Sungai Buloh', 'postcode' => 'BU1229'],
                            ['name' => 'Kampong Batu Marang', 'postcode' => 'BU1529'],
                            ['name' => 'Kampong Panchor', 'postcode' => 'BU1729'],
                            ['name' => 'Kampong Mentiri', 'postcode' => 'BU1929'],
                            ['name' => 'Perumahan Negara Mentiri Kawasan A', 'postcode' => 'BU2129'],
                            ['name' => 'Perumahan Negara Mentiri Kawasan B', 'postcode' => 'BU2229'],
                            ['name' => 'Kampong Pengkalan Sibabau', 'postcode' => 'BU2529'],
                            ['name' => 'STKRJ Tanah Jambu', 'postcode' => 'BU2729'],
                            ['name' => 'Perumahan Negara Tanah Jambu', 'postcode' => 'BU2929'],
                            ['name' => 'Perumahan Negara Panchor', 'postcode' => 'BU3129'],
                        ],
                    ],
                    [
                        'name' => 'Pangkalan Batu',
                        'kampongs' => [
                            ['name' => 'Kampong Pangkalan Batu', 'postcode' => 'BH1123'],
                            ['name' => 'Kampong Parit', 'postcode' => 'BH1023'],
                            ['name' => 'Kampong Batu Ampar', 'postcode' => 'BH1323'],
                            ['name' => 'Kampong Batang Perhentian', 'postcode' => 'BH1523'],
                            ['name' => 'Kampong Kuala Lurah', 'postcode' => 'BH1923'],
                            ['name' => 'Kampong Junjongan', 'postcode' => 'BH2123'],
                            ['name' => 'Kampong Limau Manis', 'postcode' => 'BH2323'],
                            ['name' => 'Kampong Wasan', 'postcode' => 'BH2523'],
                            ['name' => 'Kampong Masin', 'postcode' => 'BH2723'],
                            ['name' => 'Kampong Batong', 'postcode' => 'BH2923'],
                            ['name' => 'Kampong Panchor Murai', 'postcode' => 'BH3123'],
                            ['name' => 'Kampong Bebatik', 'postcode' => 'BH3223'],
                            ['name' => 'Kampong Bebuloh', 'postcode' => 'BH3323'],
                            ['name' => 'Kampong Imang', 'postcode' => 'BH2623'],
                        ],
                    ],
                    [
                        'name' => 'Sengkurong',
                        'kampongs' => [
                            ['name' => 'Kampong Sengkurong A', 'postcode' => 'BG1121'],
                            ['name' => 'Kampong Sengkurong B', 'postcode' => 'BG1321'],
                            ['name' => 'Kampong Pasai', 'postcode' => 'BG1221'],
                            ['name' => 'Kampong Tagap', 'postcode' => 'BG1521'],
                            ['name' => 'Kampong Selayun', 'postcode' => 'BG1721'],
                            ['name' => 'Kampong Mulaut', 'postcode' => 'BG2121'],
                            ['name' => 'Kampong Tanjong Nangka', 'postcode' => 'BG2321'],
                            ['name' => 'Kampong Kulapis', 'postcode' => 'BG2521'],
                            ['name' => 'Kampong Katimahar', 'postcode' => 'BG2721'],
                            ['name' => 'Kampong Lugu', 'postcode' => 'BG2921'],
                            ['name' => 'STKRJ Lugu', 'postcode' => 'BG3021'],
                            ['name' => 'Kampong Jerudong', 'postcode' => 'BG3122'],
                            ['name' => 'Kampong Peninjau', 'postcode' => 'BG3522'],
                        ],
                    ],
                    [
                        'name' => 'Serasa',
                        'kampongs' => [
                            ['name' => 'PEKAN MUARA', 'postcode' => 'BT1128'],
                            ['name' => 'Pulau Pelumpong & Tanjung Pelumpong', 'postcode' => 'BT1328'],
                            ['name' => 'Kampong Serasa', 'postcode' => 'BT1728'],
                            ['name' => 'Kampong Sabun', 'postcode' => 'BT2128'],
                            ['name' => 'Kampong Kapok', 'postcode' => 'BT2328'],
                            ['name' => 'Kampong Meragang', 'postcode' => 'BT2728'],
                            ['name' => 'Perumahan Negara Kampong Meragang', 'postcode' => 'BT2928'],
                            ['name' => 'Pulau Muara Besar', 'postcode' => 'BT3328'],
                            ['name' => 'Pulau Baru-Baru', 'postcode' => 'BT3128'],
                            ['name' => 'Pulau Pasir Tengah', 'postcode' => 'BT1628'],
                            ['name' => 'Pulau Salar', 'postcode' => 'BT1528'],
                        ],
                    ],
                    [
                        'name' => 'Burong Pingai Ayer',
                        'kampongs' => [
                            ['name' => 'Kampong Burong Pingai Ayer', 'postcode' => 'BM1126'],
                            ['name' => 'Kampong Lurong Dalam', 'postcode' => 'BM1326'],
                            ['name' => 'Kampong Pandai Besi A', 'postcode' => 'BM1526'],
                            ['name' => 'Kampong Pandai Besi B', 'postcode' => 'BM1726'],
                            ['name' => 'Kampong Sungai Pandan A', 'postcode' => 'BM1926'],
                            ['name' => 'Kampong Sungai Pandan B', 'postcode' => 'BM2126'],
                            ['name' => 'Kampong Pengiran Setia Negara', 'postcode' => 'BM2326'],
                            ['name' => 'Kampong Pekan Lama', 'postcode' => 'BM2526'],
                        ],
                    ],
                    [
                        'name' => 'Peramu',
                        'kampongs' => [
                            ['name' => 'Kampong Peramu', 'postcode' => 'BP1126'],
                            ['name' => 'Kampong Pekilong Muara', 'postcode' => 'BP1326'],
                            ['name' => 'Kampong Setia Pahlawan', 'postcode' => 'BP1526'],
                            ['name' => 'Kampong Bakut Pengiran Siraja Muda A', 'postcode' => 'BP1726'],
                            ['name' => 'Kampong Bakut Pengiran Siraja Muda B', 'postcode' => 'BP1926'],
                            ['name' => 'Kampong Lurong Sikuna', 'postcode' => 'BP2126'],
                            ['name' => 'Kampong Bakut Berumput', 'postcode' => 'BP2326'],
                        ],
                    ],
                    [
                        'name' => 'Saba',
                        'kampongs' => [
                            ['name' => 'Kampong Saba Laut', 'postcode' => 'BR1126'],
                            ['name' => 'Kampong Saba Darat A', 'postcode' => 'BR1326'],
                            ['name' => 'Kampong Saba Darat B', 'postcode' => 'BR1526'],
                            ['name' => 'Kampong Saba Ujong', 'postcode' => 'BR1726'],
                            ['name' => 'Kampong Saba Tengah', 'postcode' => 'BR1926'],
                        ],
                    ],
                    [
                        'name' => 'Sungai Kebun',
                        'kampongs' => [
                            ['name' => 'Kampong Bolkiah A', 'postcode' => 'BK1125'],
                            ['name' => 'Kampong Bolkiah B', 'postcode' => 'BK1325'],
                            ['name' => 'Kampong Setia A', 'postcode' => 'BK1525'],
                            ['name' => 'Kampong Setia B', 'postcode' => 'BK1725'],
                            ['name' => 'Kampong Sungai Siamas', 'postcode' => 'BK1925'],
                            ['name' => 'Kampong Ujong Klinik', 'postcode' => 'BK2125'],
                            ['name' => 'Kampong Sungai Kebun', 'postcode' => 'BK2325'],
                        ],
                    ],
                    [
                        'name' => 'Sungai Kedayan',
                        'kampongs' => [
                            ['name' => 'Kampong Sumbiling Lama', 'postcode' => 'BN1111'],
                        ],
                    ],
                    [
                        'name' => 'Tamoi',
                        'kampongs' => [
                            ['name' => 'Kampong Ujong Bukit', 'postcode' => 'BL1112'],
                            ['name' => 'Kampong Limbongan', 'postcode' => 'BL1312'],
                            ['name' => 'Kampong Pengiran Bendahara Lama', 'postcode' => 'BL1512'],
                            ['name' => 'Kampong Pengiran Kerma Indera Lama', 'postcode' => 'BL1712'],
                            ['name' => 'Kampong Pengiran Tajuddin Hitam', 'postcode' => 'BL1912'],
                            ['name' => 'Kampong Tamoi Tengah', 'postcode' => 'BL2112'],
                            ['name' => 'Kampong Tamoi Ujong', 'postcode' => 'BL2312'],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Tutong',
                'mukims' => [
                    [
                        'name' => 'Pekan Tutong',
                        'kampongs' => [
                            ['name' => 'Bukit Bendera', 'postcode' => 'TA1341'],
                            ['name' => 'Kampong Petani', 'postcode' => 'TA1741'],
                            ['name' => 'Kampong Panchor Papan', 'postcode' => 'TA1941'],
                            ['name' => 'Kampong Panchor Dulit', 'postcode' => 'TA2141'],
                            ['name' => 'Kampong Sengkarai', 'postcode' => 'TA2341'],
                            ['name' => 'Kampong Serambangun', 'postcode' => 'TA2541'],
                            ['name' => 'Kampong Penanjong', 'postcode' => 'TA2741'],
                            ['name' => 'Kampong Tanah Burok', 'postcode' => 'TA2941'],
                            ['name' => 'Tutong Kem', 'postcode' => 'TA3141'],
                            ['name' => 'Kampong Kuala Tutong', 'postcode' => 'TA3341'],
                            ['name' => 'Kampong Penabai', 'postcode' => 'TA3541'],
                            ['name' => 'Kampong Kandang', 'postcode' => 'TA3741'],
                            ['name' => 'Paya Pekan Tutong', 'postcode' => 'TA3941'],
                        ],
                    ],
                    [
                        'name' => 'Telisai',
                        'kampongs' => [
                            ['name' => 'Kampong Telisai', 'postcode' => 'TC1145'],
                            ['name' => 'Perumahan Negara Telisai', 'postcode' => 'TC1345'],
                            ['name' => 'Kampong Telamba', 'postcode' => 'TC1545'],
                            ['name' => 'Kampong Sungai Paku', 'postcode' => 'TC2145'],
                            ['name' => 'Kampong Danau', 'postcode' => 'TC2345'],
                            ['name' => 'Kampong Penapar-Danau', 'postcode' => 'TC2545'],
                            ['name' => 'Kampong Keramut', 'postcode' => 'TC2745'],
                            ['name' => 'Kampong Tumpuan Ugas', 'postcode' => 'TC2945'],
                            ['name' => 'Kampong Bukit Beruang', 'postcode' => 'TC3145'],
                            ['name' => 'Perumahan Negara Bukit Beruang', 'postcode' => 'TC3345'],
                            ['name' => 'Kampong Binchaya', 'postcode' => 'TC3545'],
                            ['name' => 'Kampong Pengkalan Dalai', 'postcode' => 'TC3745'],
                            ['name' => 'Kampong Penyatang', 'postcode' => 'TC3945'],
                            ['name' => 'Kampong Bukit Pasir', 'postcode' => 'TC4145'],
                        ],
                    ],
                    [
                        'name' => 'Keriam',
                        'kampongs' => [
                            ['name' => 'Kampong Keriam', 'postcode' => 'TB1141'],
                            ['name' => 'Kampong Bukit Panggal', 'postcode' => 'TB1341'],
                            ['name' => 'Kampong Luagan Dudok', 'postcode' => 'TB1541'],
                            ['name' => 'Kampong Sinaut', 'postcode' => 'TB1741'],
                            ['name' => 'Kampong Sungai Kelugos', 'postcode' => 'TB2741'],
                            ['name' => 'Kampong Kupang', 'postcode' => 'TB2941'],
                            ['name' => 'Kampong Maraburong', 'postcode' => 'TB3141'],
                            ['name' => 'Kampong Ikas', 'postcode' => 'TB3341'],
                            ['name' => 'Kawasan Padang Tembak Binturan', 'postcode' => 'TB3541'],
                        ],
                    ],
                    [
                        'name' => 'Ukong',
                        'kampongs' => [
                            ['name' => 'Kampong Ukong', 'postcode' => 'TF1147'],
                            ['name' => 'Kampong Pengkalan Ra’an', 'postcode' => 'TF1347'],
                            ['name' => 'Kampong Sungai Damit Pemadang', 'postcode' => 'TF2147'],
                            ['name' => 'Kampong Pak Bidang', 'postcode' => 'TF2947'],
                            ['name' => 'Kampong Bukit', 'postcode' => 'TF3147'],
                            ['name' => 'Kampong Long Mayan', 'postcode' => 'TF4747'],
                            ['name' => 'Hutan Simpan Andulau', 'postcode' => 'TF4947'],
                        ],
                    ],
                    [
                        'name' => 'Tanjong Maya',
                        'kampongs' => [
                            ['name' => 'Kampong Tanjong Maya', 'postcode' => 'TD1141'],
                            ['name' => 'Kampong Sebakit', 'postcode' => 'TD1341'],
                            ['name' => 'Kampong Bangunggos', 'postcode' => 'TD1541'],
                            ['name' => 'Kampong Penapar', 'postcode' => 'TD1741'],
                            ['name' => 'Kampong Pemadang', 'postcode' => 'TD1941'],
                            ['name' => 'Kampong Bukit Udal', 'postcode' => 'TD2341'],
                            ['name' => 'Kampong Lubok Pulau', 'postcode' => 'TD2541'],
                            ['name' => 'Kampong Bukit Sibut', 'postcode' => 'TD2741'],
                            ['name' => 'Kampong Liulon', 'postcode' => 'TD2941'],
                            ['name' => 'Kampong Padang', 'postcode' => 'TD3141'],
                            ['name' => 'Kampong Tanjong Panjang', 'postcode' => 'TD3341'],
                        ],
                    ],
                    [
                        'name' => 'Kiudang',
                        'kampongs' => [
                            ['name' => 'Kampong Bakiau', 'postcode' => 'TE1143'],
                            ['name' => 'Kampong Pengkalan Mau', 'postcode' => 'TE1343'],
                            ['name' => 'Kampong Kiudang', 'postcode' => 'TE1543'],
                            ['name' => 'Kampong Mungkom', 'postcode' => 'TE1743'],
                            ['name' => 'Kampong Pad Nunok', 'postcode' => 'TE1943'],
                            ['name' => 'Kampong Birau', 'postcode' => 'TE2143'],
                            ['name' => 'Kampong Luagan Timbaran', 'postcode' => 'TE2343'],
                            ['name' => 'Kampong Batang Mitus', 'postcode' => 'TE2543'],
                            ['name' => 'Kampong Kebia', 'postcode' => 'TE2743'],
                        ],
                    ],
                    [
                        'name' => 'Lamunin',
                        'kampongs' => [
                            ['name' => 'Kampong Layong', 'postcode' => 'TG1143'],
                            ['name' => 'Kampong Kuala Abang', 'postcode' => 'TG1343'],
                            ['name' => 'Kampong Lamunin', 'postcode' => 'TG2343'],
                            ['name' => 'Kampong Bukit Sulang', 'postcode' => 'TG2743'],
                            ['name' => 'Kampong Menengah', 'postcode' => 'TG2843'],
                            ['name' => 'Kampong Bintudoh', 'postcode' => 'TG2943'],
                            ['name' => 'Kampong Panchung', 'postcode' => 'TG3143'],
                            ['name' => 'Kampong Biong', 'postcode' => 'TG3343'],
                            ['name' => 'Kampong Bukit Bang Dalam', 'postcode' => 'TG3543'],
                            ['name' => 'Kampong Bukit Barun', 'postcode' => 'TG2443'],
                            ['name' => 'Hutan Simpan Bukit Ladan', 'postcode' => 'TG3943'],
                        ],
                    ],
                    [
                        'name' => 'Rambai',
                        'kampongs' => [
                            ['name' => 'Kampong Rambai', 'postcode' => 'TH1149'],
                            ['name' => 'Kampong Merimbun', 'postcode' => 'TH1349'],
                            ['name' => 'Kampong Kuala Ungar', 'postcode' => 'TH1549'],
                            ['name' => 'Kampong Benutan', 'postcode' => 'TH1749'],
                            ['name' => 'Kampong Supon Besar', 'postcode' => 'TH3149'],
                            ['name' => 'Kampong Supon Kecil', 'postcode' => 'TH3549'],
                            ['name' => 'Kampong Lalipo', 'postcode' => 'TH3749'],
                            ['name' => 'Kampong Bedawan', 'postcode' => 'TH3949'],
                            ['name' => 'Kampong Belabau', 'postcode' => 'TH4149'],
                            ['name' => 'Hutan Simpan Bukit Ladan', 'postcode' => 'TH4349'],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Belait',
                'mukims' => [
                    [
                        'name' => 'Kuala Belait',
                        'kampongs' => [
                            ['name' => 'PEKAN KUALA BELAIT', 'postcode' => 'KA1131'],
                            ['name' => 'Kampong Mumong A', 'postcode' => 'KA1531'],
                            ['name' => 'Kampong Mumong B', 'postcode' => 'KA1731'],
                            ['name' => 'Kampong Pandan A', 'postcode' => 'KA1931'],
                            ['name' => 'Kampong Pandan B', 'postcode' => 'KA2031'],
                            ['name' => 'Kampong Pandan C', 'postcode' => 'KA2131'],
                            ['name' => 'Kampong Sungai Melilit', 'postcode' => 'KA2731'],
                            ['name' => 'Kampong Sungai Teraban', 'postcode' => 'KA3331'],
                        ],
                    ],
                    [
                        'name' => 'Seria',
                        'kampongs' => [
                            ['name' => 'PEKAN SERIA Kawasan I', 'postcode' => 'KB1133'],
                            ['name' => 'PEKAN SERIA Kawasan II', 'postcode' => 'KB1233'],
                            ['name' => 'Kampong Lorong Tiga Selatan', 'postcode' => 'KB1533'],
                            ['name' => 'Kampong Sungai Bera', 'postcode' => 'KB1933'],
                            ['name' => 'Badas', 'postcode' => 'KB2133'],
                            ['name' => 'Kampong Anduki', 'postcode' => 'KB2333'],
                            ['name' => 'Perumahan Negara Lorong Tengah Seria', 'postcode' => 'KB1633'],
                            ['name' => 'Ibu Pejabat Shell', 'postcode' => 'KB2833'],
                            ['name' => 'Kawasan simpanan Gurkha Kem', 'postcode' => 'KB3733'],
                            ['name' => 'Kampong Penaga', 'postcode' => 'KB4533'],
                            ['name' => 'Kampong Perumahan Negara Penaga', 'postcode' => 'KB4733'],
                        ],
                    ],
                    [
                        'name' => 'Liang',
                        'kampongs' => [
                            ['name' => 'Kampong Sungai Liang', 'postcode' => 'KC1135'],
                            ['name' => 'Kampong Sungai Gana', 'postcode' => 'KC1335'],
                            ['name' => 'Hutan Simpan Andulau', 'postcode' => 'KC1535'],
                            ['name' => 'Kampong Keluyoh', 'postcode' => 'KC1735'],
                            ['name' => 'Kampong Perumpong', 'postcode' => 'KC1935'],
                            ['name' => 'Kampong Lilas', 'postcode' => 'KC2535'],
                            ['name' => 'Kampong Tunggulian', 'postcode' => 'KC2735'],
                            ['name' => 'Kampong Agis-Agis', 'postcode' => 'KC3335'],
                            ['name' => 'Kampong Sungai Lalit', 'postcode' => 'KC3535'],
                            ['name' => 'Kampong Sungai Kang', 'postcode' => 'KC3735'],
                            ['name' => 'Kampong Sungai Kuru', 'postcode' => 'KC3935'],
                            ['name' => 'Kampong Lumut Tersusun', 'postcode' => 'KC4135'],
                            ['name' => 'Kampong Lumut', 'postcode' => 'KC2935'],
                            ['name' => 'Kampong Sungai Bakong', 'postcode' => 'KC4535'],
                            ['name' => 'Kampong Sungai Taring', 'postcode' => 'KC4735'],
                            ['name' => 'Kampong Sungai Tali', 'postcode' => 'KC4935'],
                            ['name' => 'Perumahan Negara Lumut Kawasan 1', 'postcode' => 'KC5135'],
                            ['name' => 'Perumahan Negara Lumut Kawasan 2', 'postcode' => 'KC5335'],
                            ['name' => 'STKRJ Lumut', 'postcode' => 'KC5535'],
                            ['name' => 'Perkhemahan Lumut', 'postcode' => 'KC5735'],
                        ],
                    ],
                    [
                        'name' => 'Kuala Balai',
                        'kampongs' => [
                            ['name' => 'Kampong Kuala Balai', 'postcode' => 'KD1132'],
                            ['name' => 'Kampong Sungai Damit', 'postcode' => 'KD1532'],
                            ['name' => 'Kampong Tanjong Rangas', 'postcode' => 'KD1732'],
                            ['name' => 'Kampong Tugong', 'postcode' => 'KD1932'],
                            ['name' => 'Kampong Pangalayan', 'postcode' => 'KD2132'],
                            ['name' => 'Kampong Kajitan', 'postcode' => 'KD2332'],
                            ['name' => 'Kampong Sungai Mendaram', 'postcode' => 'KD2532'],
                            ['name' => 'Kampong Penyarap', 'postcode' => 'KD2732'],
                            ['name' => 'Kampong Lubok Tapang', 'postcode' => 'KD2932'],
                            ['name' => 'Kampong Lubok Lanyap', 'postcode' => 'KD3132'],
                            ['name' => 'Kampong Tanjong Sudai', 'postcode' => 'KD3332'],
                            ['name' => 'Kampong Sungai Lutong', 'postcode' => 'KD3532'],
                        ],
                    ],
                    [
                        'name' => 'Labi',
                        'kampongs' => [
                            ['name' => 'Kampong Bukit Puan', 'postcode' => 'KE1137'],
                            ['name' => 'Kampong Sungai Petai', 'postcode' => 'KE1337'],
                            ['name' => 'Kampong Tapang Lupak', 'postcode' => 'KE1737'],
                            ['name' => 'Kampong Tanajor', 'postcode' => 'KE1937'],
                            ['name' => 'Kampong Ratan', 'postcode' => 'KE2137'],
                            ['name' => 'Kampong Terunan', 'postcode' => 'KE2337'],
                            ['name' => 'Kampong Gatas', 'postcode' => 'KE2537'],
                            ['name' => 'Kampong Kenapol', 'postcode' => 'KE2737'],
                            ['name' => 'Kampong Terawan', 'postcode' => 'KE3137'],
                            ['name' => 'Kampong Labi Lama', 'postcode' => 'KE2437'],
                            ['name' => 'Kampong Teraja', 'postcode' => 'KE3937'],
                            ['name' => 'Kampong Labi', 'postcode' => 'KE2637'],
                            ['name' => 'Kampong Simpang Tiga', 'postcode' => 'KE3237'],
                            ['name' => 'Kampong Rampayoh', 'postcode' => 'KE3337'],
                            ['name' => 'Kampong Mendaram Kecil', 'postcode' => 'KE3537'],
                        ],
                    ],
                    [
                        'name' => 'Bukit Sawat',
                        'kampongs' => [
                            ['name' => 'Kampong Sungai Mau', 'postcode' => 'KF1138'],
                            ['name' => 'Kampong Bisut', 'postcode' => 'KF1338'],
                            ['name' => 'Kampong Bukit Sawat', 'postcode' => 'KF1738'],
                            ['name' => 'Kampong Bukit Kandol', 'postcode' => 'KF2138'],
                            ['name' => 'Kampong Merangking Ulu', 'postcode' => 'KF3138'],
                            ['name' => 'Kampong Merangking Hilir', 'postcode' => 'KF3338'],
                            ['name' => 'Kampong Tarap', 'postcode' => 'KF3738'],
                            ['name' => 'Kampong Pangkalan Siong', 'postcode' => 'KF3938'],
                            ['name' => 'Kampong Pulau Apil', 'postcode' => 'KF4538'],
                            ['name' => 'Kampong Merangking', 'postcode' => 'KF1238'],
                        ],
                    ],
                    [
                        'name' => 'Sukang',
                        'kampongs' => [
                            ['name' => 'Kampong Apak-Apak', 'postcode' => 'KG1139'],
                            ['name' => 'Kampong Kukub', 'postcode' => 'KG1739'],
                            ['name' => 'Kampong Sukang', 'postcode' => 'KG1939'],
                            ['name' => 'Kampong Dungun', 'postcode' => 'KG2139'],
                            ['name' => 'Kampong Sungai Hilir', 'postcode' => 'KG1239'],
                        ],
                    ],
                    [
                        'name' => 'Melilas',
                        'kampongs' => [
                            ['name' => 'Kampong Melilas', 'postcode' => 'KH1339'],
                            ['name' => 'Kampong Bang Garang', 'postcode' => 'KH1739'],
                            ['name' => 'Kampong Bukit Tuding', 'postcode' => 'KH1939'],
                        ],
                    ],
                ],
            ],
            [
                'name' => 'Temburong',
                'mukims' => [
                    [
                        'name' => 'Bangar',
                        'kampongs' => [
                            ['name' => 'PEKAN BANGAR', 'postcode' => 'PA1151'],
                            ['name' => 'Kawasan Perkhemahan Bangar', 'postcode' => 'PA1551'],
                            ['name' => 'Kampong Menengah', 'postcode' => 'PA1751'],
                            ['name' => 'Kampong Sungai Sulok', 'postcode' => 'PA1951'],
                            ['name' => 'Kampong Sungai Tanit', 'postcode' => 'PA2151'],
                            ['name' => 'Kampong Sungai Tanam', 'postcode' => 'PA2351'],
                            ['name' => 'Kampong Parit Belayang', 'postcode' => 'PA2551'],
                            ['name' => 'Kampong Semamang', 'postcode' => 'PA2751'],
                            ['name' => 'Kampong Bang Bulan', 'postcode' => 'PA2951'],
                            ['name' => 'Kampong Belingos', 'postcode' => 'PA3151'],
                            ['name' => 'Kampong Batang Tuau', 'postcode' => 'PA3351'],
                            ['name' => 'Kampong Seri Tanjong Belayang', 'postcode' => 'PA3551'],
                            ['name' => 'Kampong Puni', 'postcode' => 'PA3751'],
                            ['name' => 'Kampong Ujong Jalan', 'postcode' => 'PA3951'],
                            ['name' => 'Kampong Kinalong', 'postcode' => 'PA4151'],
                            ['name' => 'Kampong Lagau', 'postcode' => 'PA4351'],
                            ['name' => 'Kampong Piungan', 'postcode' => 'PA4551'],
                            ['name' => 'Kampong Batu Bejarah', 'postcode' => 'PA4751'],
                            ['name' => 'Kampong Subok', 'postcode' => 'PA4951'],
                            ['name' => 'Kampong Gadong', 'postcode' => 'PA1351'],
                            ['name' => 'Kampong Kastam Lama', 'postcode' => 'PA2051'],
                            ['name' => 'Kampong Peliunan', 'postcode' => 'PA2251'],
                            ['name' => 'Kampong Sungai Getahan', 'postcode' => 'PA2651'],
                        ],
                    ],
                    [
                        'name' => 'Labu',
                        'kampongs' => [
                            ['name' => 'Kampong Labu Estate', 'postcode' => 'PB1151'],
                            ['name' => 'Kampong Senukoh', 'postcode' => 'PB1351'],
                            ['name' => 'Kampong Piasau-Piasau', 'postcode' => 'PB1551'],
                            ['name' => 'Kampong Perdayan', 'postcode' => 'PB1751'],
                            ['name' => 'Hutan Simpan Labu', 'postcode' => 'PB1951'],
                            ['name' => 'Hutan Simpan Perdayan', 'postcode' => 'PB2151'],
                            ['name' => 'Pulau Kibi', 'postcode' => 'PB2351'],
                            ['name' => 'Pulau Kitang', 'postcode' => 'PB3351'],
                            ['name' => 'Pulau Pituat', 'postcode' => 'PB2551'],
                            ['name' => 'Pulau Selanjak', 'postcode' => 'PB2951'],
                            ['name' => 'Pulau Selirong', 'postcode' => 'PB3551'],
                            ['name' => 'Pulau Siarau', 'postcode' => 'PB2751'],
                            ['name' => 'Pulau Tarap', 'postcode' => 'PB3151'],
                        ],
                    ],
                    [
                        'name' => 'Batu Apoi',
                        'kampongs' => [
                            ['name' => 'Kampong Batu Apoi', 'postcode' => 'PC1151'],
                            ['name' => 'Kampong Sungai Radang', 'postcode' => 'PC1351'],
                            ['name' => 'Kampong Peliunan', 'postcode' => 'PC1551'],
                            ['name' => 'Kampong Gadong Baru', 'postcode' => 'PC1951'],
                            ['name' => 'Kampong Luagan', 'postcode' => 'PC2151'],
                            ['name' => 'Kampong Negalang Ering', 'postcode' => 'PC2351'],
                            ['name' => 'Kampong Negalang Unat', 'postcode' => 'PC2551'],
                            ['name' => 'Kampong Lakiun', 'postcode' => 'PC2751'],
                            ['name' => 'Kampong Tanjong Bungar', 'postcode' => 'PC2951'],
                            ['name' => 'Kampong Lamaling', 'postcode' => 'PC3151'],
                            ['name' => 'Kampong Selapon', 'postcode' => 'PC3351'],
                            ['name' => 'Kampong Sekurop', 'postcode' => 'PC3551'],
                            ['name' => 'Kampong Selilit', 'postcode' => 'PC1751'],
                            ['name' => 'Kampong Rebada', 'postcode' => 'PC3751'],
                            ['name' => 'Kampong Simbatang', 'postcode' => 'PC3951'],
                        ],
                    ],
                    [
                        'name' => 'Bokok',
                        'kampongs' => [
                            ['name' => 'Kampong Buda-Buda', 'postcode' => 'PE1151'],
                            ['name' => 'Kampong Belais Besar', 'postcode' => 'PE1351'],
                            ['name' => 'Kampong Belais Kecil', 'postcode' => 'PE1551'],
                            ['name' => 'Kampong Paya Bagangan', 'postcode' => 'PE1751'],
                            ['name' => 'Kampong Bokok', 'postcode' => 'PE1951'],
                            ['name' => 'Kampong Maniup', 'postcode' => 'PE2151'],
                            ['name' => 'Kampong Bakarut', 'postcode' => 'PE2351'],
                            ['name' => 'Kampong Simbatang', 'postcode' => 'PE2551'],
                            ['name' => 'Kampong Rataie', 'postcode' => 'PE2751'],
                            ['name' => 'Kampong Perpindahan Negara Rataie', 'postcode' => 'PE2951'],
                            ['name' => 'STKRJ Kampong Rataie', 'postcode' => 'PE3151'],
                            ['name' => 'Kampong Kenua', 'postcode' => 'PE3351'],
                            ['name' => 'Kampong Lepong', 'postcode' => 'PE3751'],
                            ['name' => 'Kampong Semabat', 'postcode' => 'PE4151'],
                            ['name' => 'Kampong Temada', 'postcode' => 'PE4351'],
                            ['name' => 'Hutan Simpan Batu Apoi', 'postcode' => 'PE4551'],
                        ],
                    ],
                    [
                        'name' => 'Amo',
                        'kampongs' => [
                            ['name' => 'Kampong Amo', 'postcode' => 'PD1151'],
                            ['name' => 'Pusat Memproses Mel, Berakas', 'postcode' => 'PD1751'],
                            ['name' => 'Kampong Sumbiling Lama', 'postcode' => 'PD1851'],
                            ['name' => 'Pejabat Besar Pos, Bandar Seri Begawan', 'postcode' => 'PD1951'],
                            ['name' => 'Kampong Sumbiling Baru', 'postcode' => 'PD2151'],
                            ['name' => 'Pejabat Pos Seri Kompleks', 'postcode' => 'PD2351'],
                            ['name' => 'Kampong Batang Duri', 'postcode' => 'PD3151'],
                            ['name' => 'Pejabat Pos Gadong', 'postcode' => 'PD2551'],
                            ['name' => 'Kampong Sibut', 'postcode' => 'PD2751'],
                            ['name' => 'Pejabat Pos Muara', 'postcode' => 'PD2951'],
                            ['name' => 'Kampong Parit', 'postcode' => 'PD2051'],
                            ['name' => 'Pejabat Pos Sengkurong', 'postcode' => 'BB3577'],
                            ['name' => 'Kampong Belaban', 'postcode' => 'BA8610'],
                            ['name' => 'Pejabat Pos Limau Manis', 'postcode' => 'BA1779'],
                            ['name' => 'Kampong Biang', 'postcode' => 'BE3978'],
                            ['name' => 'Pejabat Pos Salambigar', 'postcode' => 'BT1187'],
                            ['name' => 'Kampong Selangan', 'postcode' => 'BG1183'],
                            ['name' => 'Pejabat Pos Anggerek Desa', 'postcode' => 'BH2384'],
                            ['name' => 'Kampong Sibulu', 'postcode' => 'BC1581'],
                            ['name' => 'Pejabat Pos Bunut', 'postcode' => 'BB3780'],
                            ['name' => 'Hutan Simpan Batu Apoi POSKOD BAGI PEJABAT-PEJABAT POS SELURUH NEGARA NAMA CAWANGAN', 'postcode' => 'BF1382'],
                            ['name' => 'Pejabat Pos Lumapas', 'postcode' => 'BJ3585'],
                            ['name' => 'Pejabat Pos Tutong', 'postcode' => 'TA1194'],
                            ['name' => 'Pejabat Pos Telisai', 'postcode' => 'TC1195'],
                            ['name' => 'Pejabat Pos Lamunin', 'postcode' => 'TG2345'],
                            ['name' => 'Pejabat Pos Mumong', 'postcode' => 'KA1189'],
                            ['name' => 'Pejabat Pos Seria', 'postcode' => 'KB1190'],
                            ['name' => 'Pejabat Pos Lumut', 'postcode' => 'KC2991'],
                            ['name' => 'Pejabat Pos Labi', 'postcode' => 'KE2792'],
                            ['name' => 'Pejabat Pos Bangar', 'postcode' => 'PA1393'],
                        ],
                    ],
                ],
            ],
        ];

        DB::transaction(function () use ($dataset) {
            foreach ($dataset as $districtData) {
                $district = District::updateOrCreate(
                    ['name' => $districtData['name']],
                    ['name_bn' => $districtData['bn_name'] ?? $districtData['name']]
                );

                foreach ($districtData['mukims'] as $mukimData) {
                    $mukim = Mukim::updateOrCreate(
                        [
                            'district_id' => $district->id,
                            'name' => $mukimData['name'],
                        ],
                        [
                            'name_bn' => $mukimData['bn_name'] ?? $mukimData['name'],
                        ]
                    );

                    foreach ($mukimData['kampongs'] as $kampongData) {
                        Kampong::updateOrCreate(
                            [
                                'mukim_id' => $mukim->id,
                                'name' => $kampongData['name'],
                            ],
                            [
                                'name_bn' => $kampongData['bn_name'] ?? $kampongData['name'],
                                'postcode' => $kampongData['postcode'],
                            ]
                        );
                    }
                }
            }
        });
    }
}
